name: Proposal accepted

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  close-and-lock:
    name: close and lock accepted proposals
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: itinera-dev/actions/proposal-accepted@v1
